FROM python:3.12-slim

WORKDIR /app

COPY requirements-celery.txt .

RUN pip install --no-cache-dir -r requirements-celery.txt

COPY celery_app.py .
COPY tasks.py .

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info"]