services:
  postgres_db:
    image: postgres:15-alpine
    container_name: pricepulse_postgres
    restart: always
    environment:
      POSTGRES_USER: pulse_admin
      POSTGRES_PASSWORD: mi_contrasena_segura2908
      POSTGRES_DB: pricepulse_mvp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pricepulse_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: pricepulse_celery_worker
    restart: always
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: pricepulse_celery_beat
    restart: always
    command:
      - celery
      - -A
      - celery_app
      - beat
      - --loglevel=info
      - --schedule=/data/celerybeat-schedule
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - celery_beat_data:/data

volumes:
  postgres_data:
  celery_beat_data:
