FROM python:3.12-slim-bookworm

WORKDIR /app

COPY requirements-celery.txt .

RUN pip install --no-cache-dir -r requirements-celery.txt

RUN python -m playwright install --with-deps chromium

COPY celery_app.py .
COPY tasks.py .
COPY scraper.py .
COPY notificaciones.py .
COPY database.py .
COPY models.py .

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info"]